### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by aendrew** [rowanmanning/yeehaw#13]
Tracking who's won the most and lost the most might be fun, even if it requires a DB of some sort. Thoughts?

**Comment by rowanmanning** [comment]
It's already backed by a database, every race and bet is recorded 🙂 so this is totally possible. What's more difficult is how you display this data: if it's in Slack then we need another slash command or an option to display a leaderboard. If it's on the web then we probably need authentication rather than letting usernames etc be publicly visible.

**Comment by rowanmanning** [comment]
I already started work on an admin panel for checking on how many Slack instances and channels the race has been triggered in, but haven't got very far.

**Comment by aendrew** [comment]
Was more just thinking a `/leaderboard` Slash command or something, a web-based board is way too much of a infosec nightmare.

**Comment by rowanmanning** [comment]
I wonder whether it'd be better not to register more slash commands. Was wondering whether to add some parsing to the `/race` command so something like:

```
/race [options]              -> run a race
/race leaderboard [options]  -> view a leaderboard
```

**Comment by aendrew** [comment]
@rowanmanning Makes sense to me 👍

**Comment by rowanmanning** [comment]
This has been added now, there are two new options.

## Get a leaderboard for the current channel
```
/race leaderboard
```

## Get a global leaderboard for the whole Slack Workspace
```
/race leaderboard global
```
